"""empty message

Revision ID: 34f61b382403
Revises: e5f90311b5e1
Create Date: 2026-01-20 10:47:35.528054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34f61b382403'
down_revision = 'e5f90311b5e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.drop_constraint('followers_id_post_fkey', type_='foreignkey')
        batch_op.drop_column('id_post')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_post', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('followers_id_post_fkey', 'post', ['id_post'], ['id'])

    # ### end Alembic commands ###
