"""empty message

Revision ID: e5f90311b5e1
Revises: 0aaadd548d4c
Create Date: 2026-01-20 10:42:27.464981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f90311b5e1'
down_revision = '0aaadd548d4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.String(length=200), nullable=False))
        batch_op.drop_column('comment_text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_text', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_column('text')

    # ### end Alembic commands ###
